version: "3.2"
services:
    minecraft:
        image: minecraft-server:latest
        ports:
            - "27015:25565"
            - "27016:25575"
        volumes:
            - type: bind
              source: ./world
              target: /minecraft/world
            - type: bind
              source: ./server.properties
              target: /minecraft/server.properties
            - type: bind
              source: ./ops.json
              target: /minecraft/ops.json           
            - type: bind
              source: ./whitelist.json
              target: /minecraft/whitelist.json
            - type: bind
              source: ./banned-ips.json
              target: /minecraft/banned-ips.json           
            - type: bind
              source: ./banned-players.json
              target: /minecraft/banned-players.json
            - type: bind
              source: ./usercache.json
              target: /minecraft/usercache.json